<?php

/**
 * @file
 * Main functions for "DrupalCenter migrations".
 */

/**
 * Migration process callback to fix php-tags in legacy content.
 *
 * @param string $value
 *   The legacy content.
 *
 * @return string
 *   Content with strings like '<?php ... ?>' transformed to
 *   '&lt;?php ... ?&gt;'.
 */
function dc_migrate_legacy_fix_phptag($value) {
  if (strpos($value, '<?php') === FALSE) {
    // No need to do anything here.
    return $value;
  }
  return strtr($value, ['<?php' => '&lt;?php', '?>' => '?&gt;']);
}

/**
 * Fix bad URIs.
 *
 * @param string $value
 *   The website URL.
 *
 * @return string
 *   Website URL with correct scheme.
 */
function dc_migrate_fix_showroom_url($value) {
  if (strpos($value, 'http') === 0) {
    return $value;
  }
  return 'http://' . $value;
}
